# Application to deploy
# kubectl apply -f realworld-client-deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-client
  namespace: realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld-client
  template:
    metadata:
      labels:
        app: realworld-client
        tier: frontend
        track: stable
        service: realworld-client
    spec:
      containers:
      - name: realworld-client
        image: juanchojbarroso/realworld-client
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4100
        env:
          - name: API_ROOT
            value: "realworld-server.realworld.svc.cluster.local/api"
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 384Mi
