apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realworld-ingress
  namespace: realworld
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: realworld-client
            port:
              number: 4100
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: realworld-server
            port:
              number: 3000
